### ISSUE TITLE
An error appears on attempt to open oral reading example test

### ISSUE THREAD

**Issue by Tsitsila-O** [surveycto/timed-grid-test#34]
**Preconditions:**
- Form with the timed-grid-test field plug-in exists
- The from is downloaded to the Android Collect

**Steps to reproduce:**
1. Go to the **Fill Blank Form** menu
2. Open the form mentioned in preconditions
3. Procced a form to get to the oral reading example test

**Actual result:**
An error appears: Error loading field plugin "timed-test". Reverted to default appearance. Error: Could not find field plugin "timed-test". Please make sure the field plugin is attached to the form and try again.

**Expected result:**
The field is rendered correctly

**Comment by amrikcooper** [comment]
Hi Tsitsila,

Very sorry for the slow feedback! I didn't realise I wasn't following this repo. Thanks for your interest in EGRA on SurveyCTO, and for the report back with these steps.

I've tested this myself, and do not experience what you describe. From our README, I downloaded [the sample form](https://github.com/surveycto/timed-grid-test/raw/master/extras/sample-form/Sample%20form%20-%20Timed%20grid%20test%20field%20plug-in.xlsx), and the [field plug-in](https://github.com/surveycto/timed-grid-test/raw/master/timed-grid-test.fieldplugin.zip). From there, I deploy the sample form on a SurveyCTO server, attaching the field plug-in as an optional attachment. Importantly, I don't change the name of the zip archive containing the field plug-in, I attach it as is. When I test the sample form, no error like you describe appears.

What you describe is the standard error message when a field plug-in is specified, but a field plug-in of that name is not presently attached. The name of the field plug-in is in the file name of the zip archive, which you shouldn't change.

Please double check that the field plug-in name you're using matches the archive name. More specifically, while the file name is "timed-grid-test.fieldplugin.zip", you must specify `custom-timed-grid-test(...)`. This is all in [the product documentation](https://docs.surveycto.com/02-designing-forms/03-advanced-topics/06.using-field-plug-ins.html).

I hope this helps. Let us know if you don't come right?

**Comment by AnnaMys** [comment]
Thanks Amrik. I noticed the sample form says you must specify "custom-timed-test," rather than "custom-grid-timed-test" for the oral reading portion. I think this may be the source of the previous poster's issue.

**Comment by amrikcooper** [comment]
Hi Anna,

Thanks for your comment! Sorry for the bother to both of you, we've fixed the sample form on the main branch of this repo. The sample form had the exact problem you raised. Thanks to you both.
