### ISSUE TITLE
EGRA text not displaying on some Android devices

### ISSUE THREAD

**Issue by AnnaMys** [surveycto/timed-grid-test#43]
Hi there, we are using the EGRA reading test in our survey. It appears and works great on some devices, but won't appear on others.  The question displays and we see the text custom-egra-test(type = 'reading', duration = 60) and the start button, but then the paragraph does not appear below (see below. 

We are using SurveyCTO Collect v2.70, and I confirmed it works on other devices. (I've included the specs of the problematic device below.) Do you know how we can resolve this issue?

![Screenshot_2020-11-13-11-00-46](https://user-images.githubusercontent.com/73346960/99069692-c41d8580-25a6-11eb-83ab-fd0c6590bd44.png)
![Screenshot_2020-11-13-11-00-37](https://user-images.githubusercontent.com/73346960/99069687-c253c200-25a6-11eb-8e19-fe43c0b5e195.png)

**Comment by AnnaMys** [comment]
I think I resolved this - I redownloaded the plug-ins (timed-field-list, timed-grid-list, and button-to-advance) and attached them to the form, and that seemed to work.

**Comment by amrikcooper** [comment]
Hi Anna,

I'm glad you managed to solve! One issue might be backward compatibility. We've just recently improved backward compatibility to include devices running Android as old as 5.1.1. Redownloading probably means that you're now running our improved field plug-ins version on an older Android device. Is that true?

Thanks for the feedback and for trying this beta version of our timed-grid-test field plug-in!
