### ISSUE TITLE
All answered code not working for all assessment types

### ISSUE THREAD

**Issue by mrudasingwa** [surveycto/timed-grid-test#75]
Hi - I have the following appearance value for the oral reading fluency task.

custom-timed-grid-test(type = 'reading', duration = 60, end-after = 6, strict = 1, all-answered = 999, pause = 1)

However, when I test the situation where a respondent gets everything correct, the fail-safe behavior for when an all-answered code is not set still appears. The first item is set to incorrect and the space-delimited list of incorrect responses contains a "1". Is this a glitch or am I not setting up the code probably?

**Comment by mrudasingwa** [comment]
Adding onto the above, this also doesn't work for the number identification task:

custom-timed-grid-test(type=5, strict = 1, end-after=5, all-answered = 999, duration=60, pause = 1)

Or the addition:
custom-timed-grid-test(type=3, strict = 1, end-after = 4, duration = 60, all-answered = 999, pause = 1)

And subtraction tasks: 
custom-timed-grid-test(type=3, strict = 1, end-after = 4, duration = 60, all-answered = 999, pause = 1)

**Comment by mofya1** [comment]
For anyone viewing this issue, the solution was to include the value (in this case '999') for  the `all-answered` parameter as part of the options in the _choices_ sheet of your form as per [the documentation](https://github.com/surveycto/timed-grid-test/blob/master/README.md).
